version: '3'
services:
  backend:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    build: ./reminder_backend
    container_name: shopping-backend
    ports:
      - "8001:8000"
    volumes:
      - "./shopping_list_backend/app:/reminder_backend/app"
      - "./shopping_list_backend/requirements.txt:/reminder_backend/requirements.txt"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: shopping-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./db:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
