# Generated by Django 4.2.9 on 2024-01-08 19:51

import phonenumber_field.modelfields
from django.db import migrations


def replace_empty_phone_numbers(apps, _):
    Profile = apps.get_model("users", "Profile")
    Profile.objects.filter(phone_number="").update(phone_number=None)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_phone_number_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default=None, max_length=128, null=True, region="UA", unique=True
            ),
        ),
        migrations.RunPython(replace_empty_phone_numbers),
    ]
